### ISSUE TITLE
Deploy on Int doesn't work anymore

### ISSUE THREAD

**Issue by ponceta** [geoadmin/web-dashboard#24]
running 'rsync -rlz --delete /var/www/vhosts/web-dashboard/private/snapshots/201412101519 ip-10-220-5-250.eu-west-1.compute.internal:/var/www/vhosts/web-dashboard/private/snapshots'
 
Error : Connection timed out

unexplained error (code 255) at io.c(605) [sender=3.0.9]

(deploy.main) error while copying archive to...

@gjn Do we have anything changed anywhere that could explain that it suddendly doesn't work anymore?

**Comment by ponceta** [comment]
Int works only on one of the two int servers (the first one)

On the second I have:
![image](https://cloud.githubusercontent.com/assets/8614223/5762255/363b384c-9ce1-11e4-96dc-00193fa44829.png)

and make status gives me a dashboard is not running although I have a PID file and no error during deploy

![image](https://cloud.githubusercontent.com/assets/8614223/5762299/6d87bf96-9ce1-11e4-96b2-d79ad3923e6c.png)

**Comment by gjn** [comment]
I think you can't start/stop by hand on int becaus you lack permission to do so. PID file is created on deploy by deploy user.

try: `sudo -u deploy make start`

In general, deploy process still looks not very stable, not?

**Comment by ponceta** [comment]
Server doesn't allow zivillists? XD

![image](https://cloud.githubusercontent.com/assets/8614223/5773227/ad54000c-9d5f-11e4-96a4-c9bf947c0adf.png)

**Comment by ponceta** [comment]
For the deploy process, it looks good know. Or at least not worse as geoadmin

**Comment by ponceta** [comment]
@gjn I found 2 (x5) processes on int3 currently running. 

I have no power (can't sigterm/sigkill these :( ) can you?

**Comment by ponceta** [comment]
Solved
